import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Header } from "./ui/header";
import { Footer } from "./ui/footer";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-white text-blue-900">
        <Header />
        <div className="mt-24">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
